function figure_min(X1, Y1, marker, color, method, detect)
	%CREATEFIGURE(X1, Y1)
	%  X1:  vector of x data
	%  Y1:  vector of y data
	
	%  Auto-generated by MATLAB on 14-Nov-2016 14:20:38
	eps = 0.000001;
	% Create figure
	figure1 = figure;
	
	set(figure1, 'Units', 'inches');
	set(figure1, 'Position', [0 0 6.3 4]);

	set(figure1, 'PaperUnits', 'inches');
	set(figure1, 'PaperPosition', [0 0 6.3 4.2]);

	% Create axes
	axes1 = axes('Parent',figure1);
	hold(axes1,'on');
	
	% Create loglog
	loglog(X1+eps,Y1+eps,'Marker',marker,'Color',color, 'LineWidth', 1.5, 'MarkerFaceColor',color);

	xlim(axes1,[0.1 105]);
	ylim(axes1,[eps 105]);
	box(axes1,'on');

	set(axes1,'XMinorTick','off','XScale','log','XTick',[0.05, 0.1, 0.5, 1, 5, 10, 50, 100],...
		'YMinorTick','off','YScale',...
		'log','YTick',[eps, 10.^(-4:2)]);
    set(axes1,'fontsize',14)

	yt = get(gca, 'YTick');
	yt(1) = 0;
	set(gca,'YTickLabel',num2str(yt'));
	xt = get(gca, 'XTick');
	xt(1) = 0;
	set(gca,'XTickLabel',num2str(xt'));
	def_ax = gca;
	
	title([method,' Min Overall Error'], 'FontSize', 22)
	ylabel('Mean-Squared Error', 'FontSize', 18)
	xlabel('Data Length (sec)', 'FontSize', 18)
	saveas(gcf, [method,'_Min_',detect], 'tif')

% 	set(findall(figure1, 'type', 'text'), 'FontSize', 40)
% 	set(findall(figure1, 'type', 'title'), 'FontSize', 24)
% 	title = get(axes1,'Title')